# Generated by Django 6.0.4 on 2026-05-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="Texte original")),
                ("summary", models.TextField(verbose_name="Résumé généré")),
                ("keywords", models.JSONField(default=list, verbose_name="Mots-clés")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Résumé généré",
                "verbose_name_plural": "Résumés générés",
                "ordering": ["-created_at"],
            },
        ),
    ]
