# Generated by Django 6.0.5 on 2026-05-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="Texte original")),
                ("summary", models.TextField(verbose_name="Résumé généré")),
                ("keywords", models.JSONField(default=list, verbose_name="Mots-clés")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("student_name", models.CharField(default="Étudiant", max_length=100)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("text", "Texte brut"), ("pdf", "Fichier PDF")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Résumé généré",
                "verbose_name_plural": "Résumés générés",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("correct", "Correct ✅"),
                            ("incorrect", "À corriger ❌"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("supervisor_comment", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_request",
                        to="ai_generation.generatedsummary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de vérification",
                "ordering": ["-requested_at"],
            },
        ),
    ]
