# Generated by Django 5.0.4 on 2026-05-03 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedsummary",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Abonnement Premium"),
        ),
        migrations.AddField(
            model_name="generatedsummary",
            name="student_name",
            field=models.CharField(
                default="Étudiant", max_length=100, verbose_name="Nom étudiant"
            ),
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("correct", "Correct ✅"),
                            ("incorrect", "À corriger ❌"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut vérification",
                    ),
                ),
                (
                    "supervisor_comment",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Commentaire du superviseur",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_request",
                        to="ai_generation.generatedsummary",
                        verbose_name="Résumé concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de vérification",
                "verbose_name_plural": "Demandes de vérification",
                "ordering": ["-requested_at"],
            },
        ),
    ]
