# Generated by Django 5.0.4 on 2026-05-04 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_generation", "0002_generatedsummary_is_premium_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationrequest",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "Demande de vérification",
            },
        ),
        migrations.AddField(
            model_name="generatedsummary",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="generatedsummary",
            name="source",
            field=models.CharField(
                choices=[("text", "Texte brut"), ("pdf", "Fichier PDF")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="generatedsummary",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="generatedsummary",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("validated", "Validé"),
                    ("rejected", "Rejeté"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="generatedsummary",
            name="student_name",
            field=models.CharField(default="Étudiant", max_length=100),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("correct", "Correct ✅"),
                    ("incorrect", "À corriger ❌"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="summary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_request",
                to="ai_generation.generatedsummary",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="supervisor_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
