# Generated by Django 6.0.5 on 2026-05-27 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superviseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'superviseur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_supervises', to=settings.AUTH_USER_MODEL),
        ),
    ]
