# Generated by Django 6.0.5 on 2026-05-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_superviseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type',
            field=models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium'), ('admin', 'administrateur')], default='free', max_length=10),
        ),
    ]
