# Generated by Django 6.0.5 on 2026-05-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_abonnement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type',
            field=models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('superviseur', 'Superviseur'), ('admin', 'administrateur')], default='etudiant', max_length=20),
        ),
    ]
